/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountsResendVerificationCreateRequest
 */
export interface AccountsResendVerificationCreateRequest {
    /**
     * User\'s email address
     * @type {string}
     * @memberof AccountsResendVerificationCreateRequest
     */
    'email': string;
}

