/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountsNotificationsMarkAllAsReadCreate200Response
 */
export interface AccountsNotificationsMarkAllAsReadCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof AccountsNotificationsMarkAllAsReadCreate200Response
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsNotificationsMarkAllAsReadCreate200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountsNotificationsMarkAllAsReadCreate200Response
     */
    'count'?: number;
}

