/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountsLoginCreate200Response
 */
export interface AccountsLoginCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof AccountsLoginCreate200Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsLoginCreate200Response
     */
    'access_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsLoginCreate200Response
     */
    'refresh_token'?: string;
}

