/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AiTaskAssistant200ResponseResponse } from './ai-task-assistant200-response-response';

/**
 * 
 * @export
 * @interface AiTaskAssistant200Response
 */
export interface AiTaskAssistant200Response {
    /**
     * 
     * @type {AiTaskAssistant200ResponseResponse}
     * @memberof AiTaskAssistant200Response
     */
    'response'?: AiTaskAssistant200ResponseResponse;
}

