/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AiTaskAssistant200ResponseResponseToolResultsInner } from './ai-task-assistant200-response-response-tool-results-inner';

/**
 * AI response containing message and any actions taken
 * @export
 * @interface AiTaskAssistant200ResponseResponse
 */
export interface AiTaskAssistant200ResponseResponse {
    /**
     * AI\'s response to the user
     * @type {string}
     * @memberof AiTaskAssistant200ResponseResponse
     */
    'user_message'?: string;
    /**
     * List of actions performed
     * @type {Array<string>}
     * @memberof AiTaskAssistant200ResponseResponse
     */
    'details'?: Array<string>;
    /**
     * Detailed results of any tools executed
     * @type {Array<AiTaskAssistant200ResponseResponseToolResultsInner>}
     * @memberof AiTaskAssistant200ResponseResponse
     */
    'tool_results'?: Array<AiTaskAssistant200ResponseResponseToolResultsInner>;
}

