/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileAttachment
 */
export interface FileAttachment {
    /**
     * 
     * @type {number}
     * @memberof FileAttachment
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof FileAttachment
     */
    'task'?: number;
    /**
     * 
     * @type {number}
     * @memberof FileAttachment
     */
    'uploaded_by'?: number;
    /**
     * 
     * @type {string}
     * @memberof FileAttachment
     */
    'file'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileAttachment
     */
    'original_filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileAttachment
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FileAttachment
     */
    'uploaded_at'?: string;
}

