/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {User}
     * @memberof Profile
     */
    'user'?: User;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    'bio'?: string | null;
    /**
     * Comma-separated list of skills
     * @type {string}
     * @memberof Profile
     */
    'skills'?: string | null;
    /**
     * Details about user\'s experience
     * @type {string}
     * @memberof Profile
     */
    'experience'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    'location'?: string | null;
}

