/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'team': number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'team_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'status'?: ProjectStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'start_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'created_by'?: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'created_by_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'is_team_admin'?: string;
}

export const ProjectStatusEnum = {
    Planning: 'planning',
    Active: 'active',
    OnHold: 'on_hold',
    Completed: 'completed'
} as const;

export type ProjectStatusEnum = typeof ProjectStatusEnum[keyof typeof ProjectStatusEnum];


