/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectsGenerateProposalCreate200ResponseProposal
 */
export interface ProjectsGenerateProposalCreate200ResponseProposal {
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'project_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'estimated_duration'?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'phases'?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'resource_requirements'?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'risk_assessment'?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectsGenerateProposalCreate200ResponseProposal
     */
    'success_metrics'?: Array<string>;
}

