/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectsGenerateProposalCreate200ResponseValidation
 */
export interface ProjectsGenerateProposalCreate200ResponseValidation {
    /**
     * 
     * @type {boolean}
     * @memberof ProjectsGenerateProposalCreate200ResponseValidation
     */
    'valid'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectsGenerateProposalCreate200ResponseValidation
     */
    'warnings'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectsGenerateProposalCreate200ResponseValidation
     */
    'errors'?: Array<string>;
}

