/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner } from './projects-generate-proposal-create200-response-team-data-members-inner';

/**
 * 
 * @export
 * @interface ProjectsGenerateProposalCreate200ResponseTeamData
 */
export interface ProjectsGenerateProposalCreate200ResponseTeamData {
    /**
     * 
     * @type {number}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamData
     */
    'team_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamData
     */
    'team_name'?: string;
    /**
     * 
     * @type {Array<ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner>}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamData
     */
    'members'?: Array<ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner>;
}

