/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner
 */
export interface ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner {
    /**
     * 
     * @type {number}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner
     */
    'email'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner
     */
    'all_skills'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProjectsGenerateProposalCreate200ResponseTeamDataMembersInner
     */
    'full_experience'?: string;
}

