/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecurringTask
 */
export interface RecurringTask {
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'category': number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'project': number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'assigned_to': number | null;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'priority'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'frequency'?: RecurringTaskFrequencyEnum;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'interval'?: number;
    /**
     * 
     * @type {object}
     * @memberof RecurringTask
     */
    'days_of_week'?: object;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'day_of_month'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'custom_rule'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'max_occurrences'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof RecurringTask
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'last_triggered_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'next_trigger_at'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'occurrences_created'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecurringTask
     */
    'auto_archive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecurringTask
     */
    'preserve_history'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecurringTask
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof RecurringTask
     */
    'created_by'?: number;
}

export const RecurringTaskFrequencyEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly',
    Custom: 'custom'
} as const;

export type RecurringTaskFrequencyEnum = typeof RecurringTaskFrequencyEnum[keyof typeof RecurringTaskFrequencyEnum];


