/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'task': number;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'reminder_time': string;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'email_status'?: ReminderEmailStatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'in_app_status'?: ReminderInAppStatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'created_at'?: string;
}

export const ReminderEmailStatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Failed: 'failed'
} as const;

export type ReminderEmailStatusEnum = typeof ReminderEmailStatusEnum[keyof typeof ReminderEmailStatusEnum];
export const ReminderInAppStatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Failed: 'failed'
} as const;

export type ReminderInAppStatusEnum = typeof ReminderInAppStatusEnum[keyof typeof ReminderInAppStatusEnum];


