/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Reminder
     */
    'task': number;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'reminder_time': string;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'method'?: ReminderMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'status'?: ReminderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Reminder
     */
    'created_at'?: string;
}

export const ReminderMethodEnum = {
    Email: 'email',
    InApp: 'in_app'
} as const;

export type ReminderMethodEnum = typeof ReminderMethodEnum[keyof typeof ReminderMethodEnum];
export const ReminderStatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Failed: 'failed'
} as const;

export type ReminderStatusEnum = typeof ReminderStatusEnum[keyof typeof ReminderStatusEnum];


