/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'due_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'start_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'end_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'status'?: TaskStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'priority'?: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'user'?: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'category': number | null;
}

export const TaskStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed'
} as const;

export type TaskStatusEnum = typeof TaskStatusEnum[keyof typeof TaskStatusEnum];


