/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TasksStatsList200ResponseCategoriesInner } from './tasks-stats-list200-response-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { TasksStatsList200ResponseDailyTasks } from './tasks-stats-list200-response-daily-tasks';

/**
 * 
 * @export
 * @interface TasksStatsList200Response
 */
export interface TasksStatsList200Response {
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'total_tasks'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'completed_tasks'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'pending_tasks'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'upcoming_tasks'?: number;
    /**
     * 
     * @type {TasksStatsList200ResponseDailyTasks}
     * @memberof TasksStatsList200Response
     */
    'daily_tasks'?: TasksStatsList200ResponseDailyTasks;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof TasksStatsList200Response
     */
    'heatmap_data'?: Array<Array<number>>;
    /**
     * 
     * @type {Array<TasksStatsList200ResponseCategoriesInner>}
     * @memberof TasksStatsList200Response
     */
    'categories'?: Array<TasksStatsList200ResponseCategoriesInner>;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'completion_rate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200Response
     */
    'pending_rate'?: number;
}

