/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TasksStatsList200ResponseDailyTasks
 */
export interface TasksStatsList200ResponseDailyTasks {
    /**
     * 
     * @type {Array<string>}
     * @memberof TasksStatsList200ResponseDailyTasks
     */
    'labels'?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TasksStatsList200ResponseDailyTasks
     */
    'data'?: Array<number>;
}

