/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TasksExtractTaskDetailsCreate200Response
 */
export interface TasksExtractTaskDetailsCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'due_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'start_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'end_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'priority'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'category'?: string;
    /**
     * 
     * @type {number}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'category_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksExtractTaskDetailsCreate200Response
     */
    'status'?: string;
}

