/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TasksStatsList200ResponseProjectsInner
 */
export interface TasksStatsList200ResponseProjectsInner {
    /**
     * 
     * @type {string}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'completed'?: number;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'completion_rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'team_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TasksStatsList200ResponseProjectsInner
     */
    'team_members_count'?: number;
}

