/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TeamInvitation } from './team-invitation';
// May contain unused imports in some cases
// @ts-ignore
import type { TeamMembership } from './team-membership';

/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'owner'?: string;
    /**
     * 
     * @type {Array<TeamMembership>}
     * @memberof Team
     */
    'members'?: Array<TeamMembership>;
    /**
     * 
     * @type {Array<TeamInvitation>}
     * @memberof Team
     */
    'invitations'?: Array<TeamInvitation>;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'member_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'project_count'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'pending_invitations_count'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'is_admin'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'created_by'?: string;
}

