/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * The version of the OpenAPI document: v1
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamMembership
 */
export interface TeamMembership {
    /**
     * 
     * @type {number}
     * @memberof TeamMembership
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamMembership
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'user_email'?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamMembership
     */
    'team'?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'team_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'role'?: TeamMembershipRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof TeamMembership
     */
    'joined_at'?: string;
}

export const TeamMembershipRoleEnum = {
    Member: 'member',
    Admin: 'admin'
} as const;

export type TeamMembershipRoleEnum = typeof TeamMembershipRoleEnum[keyof typeof TeamMembershipRoleEnum];


